version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: spring-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: